---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4533770832-tpz9A5mcwy7acA9QG15zsgzN72rPi5hoHgQT4SQ
:access_token_secret: pDMLEdSw32XP1L1NGH8leMbc6Kn7L8UMqM3Wtvgrrkaro
